### ISSUE TITLE
Same chapters from different scanlators are being overwritten [MangaDex]

### ISSUE THREAD

**Issue by nnadd** [fmd-project-team/FMD#223]
The title explains it all, a great example is: https://mangadex.org/title/20679/5toubun-no-hanayome , 3 different versions of the chapter get released close to each other and only the latest one gets downloaded when my favorites update, in this case it's not really the most optimal version of the chapter I download. 
I would wager this would also happen to different titles that have multiple groups working on it.

Easy way to fix this would be to include the group in the filename, but that doesn't seem to be an option under Options > Save To > Chapter Name

**Comment by farahnur42** [comment]
![image](https://user-images.githubusercontent.com/37258115/58956066-40f7dd80-87bf-11e9-85fe-b5e84dd16ef2.png)
This should solve that issue

**Comment by nnadd** [comment]
The only thing that does is display the groups in the "Manga Info" page, it doesn't solve the issue of the downloaded chapters having the same name as that option doesn't suffix the group name to the filename.

**Comment by farahnur42** [comment]
Yeah now that I've checked I have the same issue as well, only the latest chapter gets downloaded.

**Comment by SDXC** [comment]
You're talking about filename instead of foldername. Does this mean that you don't use the "create chapter folders" option? The "Show scanlation group" does actually add a suffix but only to chapter folders.

**Comment by farahnur42** [comment]
It seems like it's fixed on my end then.

**Comment by nnadd** [comment]
> You're talking about filename instead of foldername. Does this mean that you don't use the "create chapter folders" option? The "Show scanlation group" does actually add a suffix but only to chapter folders.

Here's my setting page, FMD does create temporary folders before zipping them up for me.

![Screenshot_20190606_140722](https://user-images.githubusercontent.com/32570320/59031701-b669b980-8864-11e9-8894-0e01c579af11.png)

**Comment by fales13** [comment]
![image](https://user-images.githubusercontent.com/37041682/59155067-c8d53480-8aaa-11e9-9a52-78012efd0889.png)

works in mine, tho

**Comment by Tmp341** [comment]
@fales13 Can you show me your ``Save To`` settings? I'm suspecting something here, wanna check yours first.

**Comment by fales13** [comment]
![image](https://user-images.githubusercontent.com/37041682/59193363-a7aa3c00-8baf-11e9-9f5b-dfa2578640c0.png)

here "my save to" setting, @Tmp341

**Comment by Tmp341** [comment]
@fales13 As im suspecting, yours and mine are different from @nnadd .

I think the main cause is ``Auto generate folder based on manga's name``. So, different versions write on each other.

**Comment by fales13** [comment]
> @fales13 As im suspecting, yours and mine are different from @nnadd.
> 
> I think the main cause is he doesn't have `Auto generate folder based on manga's name` marked. So, different versions write on each other.

oh, thanks, glad to hear that

**Comment by SDXC** [comment]
@nnadd Please enable the auto create option and retry.

**Comment by nnadd** [comment]
> @nnadd Please enable the auto create option and retry.

That seems to have done it, thank you!
