### ISSUE TITLE
[Ninemanga] not working.

### ISSUE THREAD

**Issue by ZeroCool940711** [fmd-project-team/FMD#626]
When downloading somethign from Ninemanga FMD just creates the empty folder but doesnt download anything most of the time, even when it downloads something its incomplete, you have to stop the task and then resume it again, after that FMD seems to download at least a few chapters and then you have to continue repeating the previous steps multiple times if you want to get all chapters for a manga.

**Comment by Tmp341** [comment]
It has been ported to lua, should have been fixed.

**Comment by ZeroCool940711** [comment]
@Tmp341 sorry I didn't answer before, I do have the latest version, I double-checked and its still not working.

**Comment by acristobo** [comment]
Versión : 0.9.167.1
Well, Ninemanga works perfectly for me.

**Comment by acristobo** [comment]
I did the following test.
I downloaded "Bungaku Shoujo" to Ue Kawaku Yuurei.
To try ... and it worked without problem.
